Grid app
xmaczko/BusinessCard pull request #6
Opened 2023-03-09 15:05 UTC by xmaczko

2023-03-09 15:12 UTC, enel1989 requested changes

2023-03-09 15:12 UTC, enel1989 commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +                Box(modifier = Modifier.padding(bottom = 8.dp, end = 8.dp)){
Ehelyett tudsz használni spaceBy(8.dp) hívást:
https://stackoverflow.com/questions/67139925/how-to-add-dividers-between-items-in-a-lazycolumn-jetpack-compose
Így az utolsó elem alatt nem lesz ott a fölösleges padding.

2023-03-09 15:12 UTC, enel1989 commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            .size(height = 68.dp, width = 200.dp),
Szerintem jobb lenne ha a width nem fix méret lenne, hanem igazodna a képernyőhöz. Így hogy már grid-t használsz simán lehet fillMaxWidth.

2023-03-09 15:12 UTC, enel1989 commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +                    .size(width = 132.dp, height = 68.dp)
Így ide sem kell a 132.dp hanem lehet simán súlyozva hogy töltse ki a rendelkézsre álló helyet.

2023-03-09 15:12 UTC, enel1989 commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            Box(
Ezek a boxok elkerülhetőek, nyugodtan állíthatsz méretet a TopicPicure-nek

2023-03-09 15:12 UTC, enel1989 commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            painter = painterResource(id = R.drawable.ic_grain_white),
Ez egyszerűsíthető:
```
Image(
             painter = painterResource(id = if (isSystemInDarkTheme) R.drawable.ic_grain_white else R.drawable.ic_grain_black),
             contentDescription = null
         )
```

Így nem kell az nagy if.

2023-03-09 22:01 UTC, xmaczko commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            painter = painterResource(id = R.drawable.ic_grain_white),
Javítottam erre a megoldásra.

2023-03-09 22:01 UTC, xmaczko commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            Box(
Kiszedtem a Box-okat.

2023-03-09 22:01 UTC, xmaczko commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +                    .size(width = 132.dp, height = 68.dp)
Átírtam súlyozottra.

2023-03-09 22:01 UTC, xmaczko commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +            .size(height = 68.dp, width = 200.dp),
Átírtam teljes szélre.

2023-03-09 22:02 UTC, xmaczko commented on gridapp/src/main/java/com/example/gridapp/MainActivity.kt
> +                Box(modifier = Modifier.padding(bottom = 8.dp, end = 8.dp)){
Cseréltem spaceBy()-ra horizontálisan és vertikálisan is.

2023-03-10 06:56 UTC, enel1989 approved these changes
💯

2023-03-10 08:01 UTC, merged